### ISSUE TITLE
Testing chain needs updating from rinkeby to goerli

### ISSUE THREAD

**Issue by perplexedpigmy** [youfoundron/gnosis-safe-helper#1]
Lines [38 ](https://github.com/youfoundron/gnosis-safe-helper/blob/69449d6636dc03b3e4aedd2afc72844cc00f187d/src/index.ts#L38) and [48](https://github.com/youfoundron/gnosis-safe-helper/blob/69449d6636dc03b3e4aedd2afc72844cc00f187d/src/index.ts#L48)

Need an update from the deprecated and not anymore support rinkeby

**Comment by youfoundron** [comment]
Closed by #2
